
HASH_PASSWORD=$(echo $(doveadm pw -s SHA512-CRYPT -p $EMAIL_PASSWORD) |  sed -e "s/{SHA512-CRYPT}//g")

DOMAIN_PUNNY=$(echo $DOMAIN_EAI | idn)

mariadb --default-character-set=utf8 -h mail-db -u root -p$MARIADB_PASSWORD << MYSQL

CREATE DATABASE IF NOT EXISTS $EAI_DB CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE USER IF NOT EXISTS $EAI_USER_DB IDENTIFIED BY '$EAI_PASSWORD_DB';
GRANT SELECT, INSERT, UPDATE, DELETE ON $EAI_DB.* TO $EAI_USER_DB;

USE $EAI_DB;
CREATE TABLE IF NOT EXISTS domains (domain varchar(512) NOT NULL, PRIMARY KEY (domain));
CREATE TABLE IF NOT EXISTS forwardings (source varchar(512) NOT NULL, destination varchar(512) NOT NULL, PRIMARY KEY (source));
CREATE TABLE IF NOT EXISTS users (email varchar(512) NOT NULL, password varchar(512) NOT NULL, origin varchar(512) NOT NULL, PRIMARY KEY (email));

INSERT IGNORE INTO domains (domain) VALUES ('$DOMAINNAME');
INSERT IGNORE INTO domains (domain) VALUES ('$DOMAIN_EAI');
INSERT IGNORE INTO domains (domain) VALUES ('$DOMAIN_PUNNY');
INSERT IGNORE INTO users (email, password, origin) VALUES ('$EMAIL_USER@$DOMAINNAME', '$HASH_PASSWORD', '$EMAIL_USER@$DOMAINNAME');
INSERT IGNORE INTO users (email, password, origin) VALUES ('$EMAIL_EAI_USER@$DOMAIN_EAI', '$HASH_PASSWORD', '$EMAIL_USER@$DOMAINNAME');
INSERT IGNORE INTO users (email, password, origin) VALUES ('$EMAIL_EAI_USER@$DOMAIN_PUNNY', '$HASH_PASSWORD', '$EMAIL_USER@$DOMAINNAME');
INSERT IGNORE INTO forwardings (source,destination) VALUES ('$EMAIL_EAI_USER@$DOMAIN_EAI', '$EMAIL_USER@$DOMAINNAME');
INSERT IGNORE INTO forwardings (source,destination) VALUES ('$EMAIL_EAI_USER@$DOMAIN_PUNNY', '$EMAIL_USER@$DOMAINNAME');

CREATE DATABASE IF NOT EXISTS $RC_DB CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE USER IF NOT EXISTS $RC_USER IDENTIFIED BY '$RC_PASSWORD';
GRANT ALL PRIVILEGES ON $RC_DB.* TO $RC_USER;
MYSQL
